// Generated by the Phi compiler. Do not edit.
#include <stdint.h>

typedef struct pt27 pt27;
struct pt27 { uint8_t elems[3]; }; // [3]u8
typedef struct pt22 pt22;
struct pt22 { uint8_t* ptr; uint64_t len; }; // []u8
typedef struct pt38 pt38;
struct pt38 { union { uint64_t m0; }; uint8_t tag; }; // u64 | none

static const pt27 pd28 = { .elems = { ((uint8_t)121ULL), ((uint8_t)101ULL), ((uint8_t)115ULL) } };

extern int64_t write(int32_t, uint8_t*, uint64_t);

static void p0_main(void);
static void p1_print(pt22 v0 /* text */);

// fn main
static void p0_main(void) {

b0:;
    goto b1;
b1:;
    p1_print(((pt22){ (uint8_t*)pd28.elems, 3 }));
    goto b2;
b2:;
    return;
}

// fn print
static void p1_print(pt22 v0 /* text */) {
    pt22 s1; // rest
    pt22 v3;
    uint64_t v4;
    uint8_t v5;
    pt22 v6;
    uint8_t* v7;
    pt22 v8;
    uint64_t v9;
    int64_t v10;
    uint8_t v11;
    pt38 v12;
    pt38 s13;
    pt38 v15;
    uint64_t v16;
    pt22 v17;
    uint64_t v18;
    pt22 v20;

b0:;
    s1 = v0;
    goto b1;
b1:;
    goto b2;
b2:;
    v3 = s1;
    v4 = v3.len;
    v5 = !(v4 == ((uint64_t)0ULL));
    if (v5 == 0) goto b3; else goto b4;
b3:;
    return;
b4:;
    goto b5;
b5:;
    v6 = s1;
    v7 = v6.ptr;
    v8 = s1;
    v9 = v8.len;
    v10 = write(((int32_t)1LL), v7, v9);
    v11 = !(v10 <= ((int64_t)0LL));
    if (v11 == 0) goto b6; else goto b7;
b6:;
    return;
b7:;
    goto b8;
b8:;
    if (v10 >= 0 && (uint64_t)v10 <= ((uint64_t)18446744073709551615ULL)) v12 = (pt38){ .m0 = (uint64_t)v10, .tag = 0 }; else v12 = (pt38){ .tag = 1 };
    s13 = v12;
    if (v12.tag == 0) goto b10; else goto b9;
b9:;
    return;
b10:;
    v15 = s13;
    v16 = v15.m0;
    v17 = s1;
    v18 = v17.len;
    if ((uint64_t)v16 > (uint64_t)v18) __builtin_trap();
    v20 = (pt22){ v17.ptr + v16, (uint64_t)(v18 - v16) };
    s1 = v20;
    goto b1;
}

int main(void) {
    p0_main();
    return 0;
}
