// Generated by the Phi compiler. Do not edit.
#include <stdint.h>

static int64_t p0_checked(int64_t v0 /* a */, int64_t v1 /* b */);
static int64_t p1_divided(int64_t v0 /* a */, int64_t v1 /* b */);
static uint32_t p2_shifted(uint32_t v0 /* a */, uint32_t v1 /* b */);
static int32_t p3_negated(int32_t v0 /* a */);
static uint8_t p4_compared(int64_t v0 /* a */, int64_t v1 /* b */);
static double p5_floated(double v0 /* a */, double v1 /* b */);
static void p6_main(void);

#line 1 "test/pass/checked_arithmetic.phi"
// fn checked
static int64_t p0_checked(int64_t v0 /* a */, int64_t v1 /* b */) {
    int64_t v2;
    int64_t v3;
    int64_t v4;

b0:;
#line 2 "test/pass/checked_arithmetic.phi"
    if (__builtin_mul_overflow(v1, v0, &v2)) __builtin_trap();
#line 2 "test/pass/checked_arithmetic.phi"
    if (__builtin_add_overflow(v0, v2, &v3)) __builtin_trap();
#line 2 "test/pass/checked_arithmetic.phi"
    if (__builtin_sub_overflow(v3, v1, &v4)) __builtin_trap();
    return v4;
}

#line 5 "test/pass/checked_arithmetic.phi"
// fn divided
static int64_t p1_divided(int64_t v0 /* a */, int64_t v1 /* b */) {
    int64_t v2;
    int64_t v3;
    int64_t v4;

b0:;
#line 6 "test/pass/checked_arithmetic.phi"
    if (v1 == 0) __builtin_trap();
    if (v0 == ((int64_t)(-9223372036854775807LL - 1)) && v1 == -1) __builtin_trap();
    v2 = v0 / v1;
#line 6 "test/pass/checked_arithmetic.phi"
    if (v1 == 0) __builtin_trap();
    v3 = (v1 == -1) ? 0 : v0 % v1;
#line 6 "test/pass/checked_arithmetic.phi"
    if (__builtin_add_overflow(v2, v3, &v4)) __builtin_trap();
    return v4;
}

#line 9 "test/pass/checked_arithmetic.phi"
// fn shifted
static uint32_t p2_shifted(uint32_t v0 /* a */, uint32_t v1 /* b */) {
    uint32_t v2;
    uint32_t v3;
    uint32_t v4;
    uint32_t v5;
    uint32_t v6;

b0:;
#line 10 "test/pass/checked_arithmetic.phi"
    if ((uint64_t)v1 >= 32) __builtin_trap();
    v2 = (uint32_t)((uint32_t)v0 << v1);
#line 10 "test/pass/checked_arithmetic.phi"
    if ((uint64_t)v1 >= 32) __builtin_trap();
    v3 = (uint32_t)(v0 >> v1);
#line 10 "test/pass/checked_arithmetic.phi"
    v4 = (uint32_t)~v0;
#line 10 "test/pass/checked_arithmetic.phi"
    v5 = v3 & v4;
#line 10 "test/pass/checked_arithmetic.phi"
    v6 = v2 | v5;
    return v6;
}

#line 13 "test/pass/checked_arithmetic.phi"
// fn negated
static int32_t p3_negated(int32_t v0 /* a */) {
    int32_t v1;

b0:;
#line 14 "test/pass/checked_arithmetic.phi"
    if (__builtin_sub_overflow((int32_t)0, v0, &v1)) __builtin_trap();
    return v1;
}

#line 17 "test/pass/checked_arithmetic.phi"
// fn compared
static uint8_t p4_compared(int64_t v0 /* a */, int64_t v1 /* b */) {
    uint8_t v2;

b0:;
#line 18 "test/pass/checked_arithmetic.phi"
    v2 = !(v0 < v1);
    return v2;
}

#line 21 "test/pass/checked_arithmetic.phi"
// fn floated
static double p5_floated(double v0 /* a */, double v1 /* b */) {
    double v2;
    double v3;
    double v4;

b0:;
#line 22 "test/pass/checked_arithmetic.phi"
    v2 = v0 * v1;
#line 22 "test/pass/checked_arithmetic.phi"
    v3 = v0 - v1;
#line 22 "test/pass/checked_arithmetic.phi"
    if (v3 == 0) __builtin_trap();
    v4 = v2 / v3;
    return v4;
}

#line 25 "test/pass/checked_arithmetic.phi"
// fn main
static void p6_main(void) {
    int64_t v0;
    int64_t v1;
    uint32_t v2;
    int32_t v3;
    uint8_t v4;
    double v5;

b0:;
#line 26 "test/pass/checked_arithmetic.phi"
    v0 = p0_checked(((int64_t)6LL), ((int64_t)7LL));
#line 27 "test/pass/checked_arithmetic.phi"
    v1 = p1_divided(((int64_t)6LL), ((int64_t)7LL));
#line 28 "test/pass/checked_arithmetic.phi"
    v2 = p2_shifted(((uint32_t)6ULL), ((uint32_t)7ULL));
#line 29 "test/pass/checked_arithmetic.phi"
    v3 = p3_negated(((int32_t)6LL));
#line 30 "test/pass/checked_arithmetic.phi"
    v4 = p4_compared(((int64_t)6LL), ((int64_t)7LL));
#line 31 "test/pass/checked_arithmetic.phi"
    v5 = p5_floated(((double)0x1.ap2), ((double)0x1.ep2));
    return;
}

int main(void) {
    p6_main();
    return 0;
}
