// Generated by the Phi compiler. Do not edit.
#include <stdint.h>

_Static_assert(sizeof(void *) == 8, "phi lays programs out for 64-bit targets for now");

typedef struct pt28 pt28;
struct pt28 { uint8_t elems[14]; }; // [14]u8
_Static_assert(sizeof(pt28) == 14, "phi sized [14]u8 at 14 bytes");
_Static_assert(_Alignof(pt28) == 1, "phi aligned [14]u8 at 1 bytes");
typedef struct pt15 pt15;
struct pt15 { uint8_t* ptr; uint64_t len; }; // []u8
_Static_assert(sizeof(pt15) == 16, "phi sized []u8 at 16 bytes");
_Static_assert(_Alignof(pt15) == 8, "phi aligned []u8 at 8 bytes");
typedef struct pt42 pt42;
struct pt42 { union { uint64_t m0; }; uint8_t tag; }; // u64 | none
_Static_assert(sizeof(pt42) == 16, "phi sized u64 | none at 16 bytes");
_Static_assert(_Alignof(pt42) == 8, "phi aligned u64 | none at 8 bytes");

static const pt28 pd29 = { .elems = { ((uint8_t)72ULL), ((uint8_t)101ULL), ((uint8_t)108ULL), ((uint8_t)108ULL), ((uint8_t)111ULL), ((uint8_t)44ULL), ((uint8_t)32ULL), ((uint8_t)119ULL), ((uint8_t)111ULL), ((uint8_t)114ULL), ((uint8_t)108ULL), ((uint8_t)100ULL), ((uint8_t)33ULL), ((uint8_t)10ULL) } };

extern int64_t write(int32_t, uint8_t*, uint64_t);

static void p0_main(void);
static void p1_print(pt15 v0 /* text */);

#line 3 "test/pass/hello.phi"
// fn main
static void p0_main(void) {

b0:;
#line 4 "test/pass/hello.phi"
    p1_print(((pt15){ (uint8_t*)pd29.elems, 14 }));
    return;
}

#line 4 "lib/std/io.phi"
// fn print
static void p1_print(pt15 v0 /* text */) {
    pt15 s1; // rest
    pt15 v3;
    uint64_t v4;
    uint8_t v5;
    pt15 v6;
    uint8_t* v7;
    pt15 v8;
    uint64_t v9;
    int64_t v10;
    uint8_t v11;
    pt42 v12;
    pt42 s13;
    pt42 v15;
    uint64_t v16;
    pt15 v17;
    uint64_t v18;
    pt15 v20;

b0:;
#line 5 "lib/std/io.phi"
    s1 = v0;
    goto b1;
b1:;
    goto b2;
b2:;
#line 7 "lib/std/io.phi"
    v3 = s1;
#line 7 "lib/std/io.phi"
    v4 = v3.len;
#line 7 "lib/std/io.phi"
    v5 = !(v4 == ((uint64_t)0ULL));
    if (v5 == 0) goto b3; else goto b4;
b3:;
    return;
b4:;
    goto b5;
b5:;
#line 10 "lib/std/io.phi"
    v6 = s1;
#line 10 "lib/std/io.phi"
    v7 = v6.ptr;
#line 10 "lib/std/io.phi"
    v8 = s1;
#line 10 "lib/std/io.phi"
    v9 = v8.len;
#line 10 "lib/std/io.phi"
    v10 = write(((int32_t)1LL), v7, v9);
#line 11 "lib/std/io.phi"
    v11 = !(v10 <= ((int64_t)0LL));
    if (v11 == 0) goto b6; else goto b7;
b6:;
    return;
b7:;
    goto b8;
b8:;
#line 14 "lib/std/io.phi"
    if (v10 >= 0 && (uint64_t)v10 <= ((uint64_t)18446744073709551615ULL)) v12 = (pt42){ .m0 = (uint64_t)v10, .tag = 0 }; else v12 = (pt42){ .tag = 1 };
#line 14 "lib/std/io.phi"
    s13 = v12;
    if (v12.tag == 0) goto b10; else goto b9;
b9:;
    return;
b10:;
#line 14 "lib/std/io.phi"
    v15 = s13;
#line 14 "lib/std/io.phi"
    v16 = v15.m0;
#line 15 "lib/std/io.phi"
    v17 = s1;
#line 15 "lib/std/io.phi"
    v18 = v17.len;
#line 15 "lib/std/io.phi"
    if ((uint64_t)v16 > (uint64_t)v18) __builtin_trap();
#line 15 "lib/std/io.phi"
    v20 = (pt15){ v17.ptr + v16, (uint64_t)(v18 - v16) };
#line 15 "lib/std/io.phi"
    s1 = v20;
    goto b1;
}

int main(void) {
    p0_main();
    return 0;
}
