// Generated by the Phi compiler. Do not edit.
#include <stdint.h>

_Static_assert(sizeof(void *) == 8, "phi lays an address out at 8 bytes");

static void p0_main(void);

#line 1 "test/pass/minimal.phi"
// fn main
static void p0_main(void) {

b0:;
    return;
}

int main(void) {
    p0_main();
    return 0;
}
