// Generated by the Phi compiler. Do not edit.
#include <stdint.h>

_Static_assert(sizeof(void *) == 8, "phi lays an address out at 8 bytes");

typedef struct pt15 pt15;
struct pt15 { int64_t f0 /* x */; int64_t f1 /* y */; }; // Point
_Static_assert(sizeof(pt15) == 16, "phi sized Point at 16 bytes");
_Static_assert(_Alignof(pt15) == 8, "phi aligned Point at 8 bytes");

static pt15 p1_make(int64_t v0 /* x */);
static int64_t p3_slide(pt15 v0 /* p */);
static void p0_main(void);

#line 6 "test/pass/structs.phi"
// fn make
static pt15 p1_make(int64_t v0 /* x */) {
    int64_t v1;
    pt15 v2;

b0:;
#line 7 "test/pass/structs.phi"
    if (__builtin_add_overflow(v0, ((int64_t)1LL), &v1)) __builtin_trap();
#line 7 "test/pass/structs.phi"
    v2 = (pt15){ .f0 = v0, .f1 = v1 };
    return v2;
}

#line 10 "test/pass/structs.phi"
// fn slide
static int64_t p3_slide(pt15 v0 /* p */) {
    int64_t v1;
    int64_t v2;
    int64_t v3;

b0:;
#line 11 "test/pass/structs.phi"
    v1 = v0.f0;
#line 11 "test/pass/structs.phi"
    v2 = v0.f1;
#line 11 "test/pass/structs.phi"
    if (__builtin_add_overflow(v1, v2, &v3)) __builtin_trap();
    return v3;
}

#line 14 "test/pass/structs.phi"
// fn main
static void p0_main(void) {
    pt15 v0;
    pt15 s1; // p
    int64_t* v3;
    pt15 v4;
    int64_t v5;
    int64_t v6;
    pt15 v8;
    int64_t v9;

b0:;
#line 15 "test/pass/structs.phi"
    v0 = p1_make(((int64_t)20LL));
#line 15 "test/pass/structs.phi"
    s1 = v0;
#line 16 "test/pass/structs.phi"
    v3 = &(&s1)->f1;
#line 16 "test/pass/structs.phi"
    v4 = s1;
#line 16 "test/pass/structs.phi"
    v5 = v4.f0;
#line 16 "test/pass/structs.phi"
    if (__builtin_add_overflow(v5, ((int64_t)22LL), &v6)) __builtin_trap();
#line 16 "test/pass/structs.phi"
    (*v3) = v6;
#line 17 "test/pass/structs.phi"
    v8 = s1;
#line 17 "test/pass/structs.phi"
    v9 = p3_slide(v8);
    return;
}

int main(void) {
    p0_main();
    return 0;
}
