//! The C backend.

const std = @import("std");
const assert = std.debug.assert;
const Allocator = std.mem.Allocator;
const Writer = std.Io.Writer;

const AST = @import("../AST.zig");
const Compilation = @import("../Compilation.zig");
const IR = @import("../IR.zig");
const Layout = @import("../Layout.zig");
const Pool = @import("../Pool.zig");
const Source = @import("../Source.zig");
const spell = @import("../util/spell.zig");

const Ref = IR.Ref;

comp: *Compilation,
gpa: Allocator,
/// One typedef per demanded type, in first-demand order.
types: Writer.Allocating,
/// Storage for every constant that needs an address.
data: Writer.Allocating,
/// One declaration per extern function a body calls.
externs: Writer.Allocating,
/// One prototype per function, so definition order never matters.
protos: Writer.Allocating,
/// The function definitions.
code: Writer.Allocating,
/// Types whose typedef is already written.
typed: std.AutoHashMapUnmanaged(Pool.Index, void),
/// Constants whose storage is already written.
stored: std.AutoHashMapUnmanaged(Pool.Index, void),
/// Extern instances already declared.
declared: std.AutoHashMapUnmanaged(Pool.Instance, void),
/// The body being lowered.
func: IR.Func,

const C = @This();

pub const Error = error{ OutOfMemory, Refused };

/// Buffer writes fail only on allocation, so `emit` folds this into `Error`.
const Fail = error{ OutOfMemory, WriteFailed, Refused };

const type_depth_max = Layout.depth_max;

const preamble =
    \\// Generated by the Phi compiler. Do not edit.
    \\#include <stdint.h>
    \\
    \\
;

pub const Entry = union(enum) {
    instance: Pool.Instance,
    /// Nothing reported. The caller says the file has no 'main'.
    missing,
    /// Already reported at the declaration.
    refused,
};

/// The `fn main()` a program starts at, in the root module.
pub fn entryOf(comp: *Compilation) Allocator.Error!Entry {
    assert(comp.hasErrors() == false);
    assert(comp.modules.items.len > 0);

    const decl_index = comp.moduleAt(.root).findDecl("main") orelse return .missing;
    const decl = comp.declAt(decl_index);

    if (decl.kind != .fn_decl) {
        try reportEntry(comp, decl.node, "a program starts at 'fn main()', and this " ++
            "'main' is not a function", "not a function");
        return .refused;
    }
    if (comp.typeParamCount(decl_index) > 0) {
        try reportEntry(comp, decl.node, "a program starts at a plain 'fn main()', and " ++
            "this one is generic", "cannot be generic");
        return .refused;
    }

    const view = comp.treeOf(.root).viewOf(decl.node).fn_decl;
    var shaped = true;
    if (view.params.len > 0) {
        try reportEntry(comp, decl.node, "'main' takes parameters, and the start of a " ++
            "program takes none", "no parameters here");
        shaped = false;
    }
    if (view.return_type.unwrap()) |returned| {
        try reportEntry(comp, returned, "'main' returns a value, and the start of a " ++
            "program returns nothing", "no return type here");
        shaped = false;
    }
    if (shaped == false) return .refused;

    // a clean compile instantiated and lowered every plain root function
    const instance = decl.plain_instance.unwrap().?;
    assert(comp.instanceAt(instance).func != .none);
    return .{ .instance = instance };
}

fn reportEntry(
    comp: *Compilation,
    node: AST.Node.Index,
    message: []const u8,
    label: []const u8,
) Allocator.Error!void {
    try comp.reportNode(.root, node, .{
        .code = .entry_signature,
        .message = message,
        .label = label,
    });
}

/// The whole program as C, ending in an `int main` that calls the entry.
pub fn emit(
    comp: *Compilation,
    entry: Pool.Instance,
    out: *Writer,
) (Writer.Error || Error)!void {
    assert(comp.hasErrors() == false);
    assert(comp.instanceAt(entry).func != .none);

    const gpa = comp.gpa;
    var backend: C = .{
        .comp = comp,
        .gpa = gpa,
        .types = .init(gpa),
        .data = .init(gpa),
        .externs = .init(gpa),
        .protos = .init(gpa),
        .code = .init(gpa),
        .typed = .empty,
        .stored = .empty,
        .declared = .empty,
        .func = undefined,
    };
    defer backend.deinit();

    backend.writeProgram(entry) catch |err| switch (err) {
        // a buffer write fails only when its allocation does
        error.WriteFailed, error.OutOfMemory => return error.OutOfMemory,
        error.Refused => return error.Refused,
    };

    try out.writeAll(preamble);
    for ([_]*Writer.Allocating{
        &backend.types,
        &backend.data,
        &backend.externs,
        &backend.protos,
    }) |section| {
        if (section.written().len == 0) continue;
        try out.writeAll(section.written());
        try out.writeByte('\n');
    }
    try out.writeAll(backend.code.written());
}

fn writeProgram(backend: *C, entry: Pool.Instance) Fail!void {
    const comp = backend.comp;

    const instance_count = comp.instances.items.len;
    var raw: u32 = 0;
    while (raw < instance_count) : (raw += 1) {
        const instance: Pool.Instance = .from(raw);
        const func_index = comp.instanceAt(instance).func.unwrap() orelse continue;

        try backend.writeSignature(&backend.protos.writer, instance, .local);
        try backend.protos.writer.writeAll(";\n");
        try backend.writeFunc(instance, comp.funcAt(func_index));
    }
    // bodies never commit past checking, so nothing added since carries one
    for (comp.instances.items[instance_count..]) |late| assert(late.func == .none);

    try backend.code.writer.writeAll("int main(void) {\n    ");
    try writeFuncName(backend.comp, &backend.code.writer, entry);
    try backend.code.writer.writeAll("();\n    return 0;\n}\n");
}

fn deinit(backend: *C) void {
    const gpa = backend.gpa;
    for ([_]*Writer.Allocating{
        &backend.types, &backend.data, &backend.externs, &backend.protos, &backend.code,
    }) |section| section.deinit();
    backend.typed.deinit(gpa);
    backend.stored.deinit(gpa);
    backend.declared.deinit(gpa);
    backend.* = undefined;
}

// signatures

/// `p<instance>_<name>`, unique because the instance is.
fn writeFuncName(comp: *const Compilation, writer: *Writer, instance: Pool.Instance) Fail!void {
    const decl = comp.declAt(comp.instanceDecl(instance));
    assert(decl.kind == .fn_decl);
    try writer.print("p{d}_{s}", .{ instance.int(), comp.pool.stringText(decl.name) });
}

const Linkage = enum { local, external };

fn writeSignature(
    backend: *C,
    writer: *Writer,
    instance: Pool.Instance,
    linkage: Linkage,
) Fail!void {
    const comp = backend.comp;
    assert(comp.instanceAt(instance).rows_state == .done);

    try writer.writeAll(if (linkage == .local) "static " else "extern ");
    const return_type = comp.instanceType(instance);
    if (return_type == .void_type) {
        try writer.writeAll("void");
    } else {
        try backend.writeTypeName(writer, return_type, 0);
    }
    try writer.writeByte(' ');
    switch (linkage) {
        .local => try writeFuncName(comp, writer, instance),
        .external => {
            const decl = comp.declAt(comp.instanceDecl(instance));
            try writer.writeAll(comp.pool.stringText(decl.name));
        },
    }
    try backend.writeParams(writer, instance, linkage == .local);
}

fn writeParams(
    backend: *C,
    writer: *Writer,
    instance: Pool.Instance,
    named: bool,
) Fail!void {
    const comp = backend.comp;

    try writer.writeByte('(');
    const rows = comp.instanceAt(instance).rows;
    if (rows.len == 0) try writer.writeAll("void");
    var position: u32 = 0;
    while (position < rows.len) : (position += 1) {
        // by index, because a parameter's struct type can grow the rows table
        const row = comp.rowAt(.from(rows.at(position)));
        if (position > 0) try writer.writeAll(", ");
        try backend.writeTypeName(writer, row.type, 0);
        if (named) {
            try writer.print(" v{d} /* {s} */", .{ position, comp.pool.stringText(row.name) });
        }
    }
    try writer.writeByte(')');
}

/// The declaration an extern call needs, written once into its own section.
fn ensureExtern(backend: *C, instance: Pool.Instance) Fail!void {
    const comp = backend.comp;
    assert(comp.declAt(comp.instanceDecl(instance)).kind == .extern_fn);

    const gop = try backend.declared.getOrPut(backend.gpa, instance);
    if (gop.found_existing) return;

    try backend.writeSignature(&backend.externs.writer, instance, .external);
    try backend.externs.writer.writeAll(";\n");
}

// types

/// What one union is in C
const UnionForm = union(enum) {
    tag_only,
    /// The member that keeps the address.
    /// See `Layout.nice`
    niche: Pool.Index,
    tagged,
};

fn unionFormOf(pool: *const Pool, index: Pool.Index) UnionForm {
    assert(pool.isUnion(index));

    if (Layout.niche(pool, index)) |carrier| {
        assert(pool.unionHas(index, carrier));
        return .{ .niche = carrier };
    }
    for (pool.unionMembers(index)) |member| {
        if (pool.keyOf(member) != .type_unit) return .tagged;
    }
    return .tag_only;
}

/// The C spelling of a type, its typedef demanded on the way.
fn writeTypeName(
    backend: *C,
    writer: *Writer,
    index: Pool.Index,
    depth: u32,
) Fail!void {
    assert(depth < type_depth_max);
    const pool = &backend.comp.pool;

    switch (pool.keyOf(index)) {
        .type_simple => |simple| try writer.writeAll(simpleName(simple)),
        // no zero-sized C object, so a unit is a byte no one reads
        .type_unit => try writer.writeAll("uint8_t"),
        .type_pointer => |pointer| {
            try backend.writeTypeName(writer, pointer.child, depth + 1);
            try writer.writeByte('*');
        },
        .type_slice => |slice| {
            // permission erased, because the checker retypes `[]var T` to `[]T`
            // without an instruction, so both forms share one C type
            const canonical = try pool.intern(backend.gpa, .{
                .type_slice = .{ .child = slice.child, .mutable = false },
            });
            try backend.ensureTypedef(canonical, depth);
            try writer.print("pt{d}", .{canonical.int()});
        },
        .type_array, .type_struct => {
            try backend.ensureTypedef(index, depth);
            try writer.print("pt{d}", .{index.int()});
        },
        .type_union => switch (unionFormOf(pool, index)) {
            .tag_only => try writer.writeAll("uint8_t"),
            .niche => |carrier| try backend.writeTypeName(writer, carrier, depth + 1),
            .tagged => {
                try backend.ensureTypedef(index, depth);
                try writer.print("pt{d}", .{index.int()});
            },
        },
        .value_int, .value_float, .value_aggregate => unreachable,
        .value_unit, .value_union, .value_slice, .value_splat => unreachable,
    }
}

fn simpleName(simple: Pool.SimpleType) []const u8 {
    return switch (simple) {
        .i8 => "int8_t",
        .i16 => "int16_t",
        .i32 => "int32_t",
        .i64 => "int64_t",
        .u8 => "uint8_t",
        .u16 => "uint16_t",
        .u32 => "uint32_t",
        .u64 => "uint64_t",
        .f32 => "float",
        .f64 => "double",
        // a committed body types no instruction with these
        .poison, .void, .untyped_int, .untyped_float, .untyped_aggregate => unreachable,
    };
}

fn ensureTypedef(backend: *C, index: Pool.Index, depth: u32) Fail!void {
    assert(depth < type_depth_max);
    const comp = backend.comp;
    const pool = &comp.pool;

    const gop = try backend.typed.getOrPut(backend.gpa, index);
    if (gop.found_existing) return;
    try backend.types.writer.print("typedef struct pt{d} pt{d};\n", .{
        index.int(),
        index.int(),
    });

    var body: Writer.Allocating = .init(backend.gpa);
    defer body.deinit();
    const w = &body.writer;

    try w.print("struct pt{d} {{ ", .{index.int()});
    switch (pool.keyOf(index)) {
        .type_slice => |slice| {
            // permission is the checker's fact alone, so both forms share this
            assert(slice.mutable == false);
            try backend.writeTypeName(w, slice.child, depth + 1);
            try w.writeAll("* ptr; uint64_t len; ");
        },
        .type_array => |array| {
            try backend.writeTypeName(w, array.child, depth + 1);
            try w.print(" elems[{d}]; ", .{array.len});
        },
        .type_union => {
            // only the tagged form owns a typedef, `writeTypeName` spells the rest
            assert(unionFormOf(pool, index) == .tagged);
            try w.writeAll("union { ");
            const count = pool.unionMemberCount(index);
            var at: u32 = 0;
            while (at < count) : (at += 1) {
                const member = pool.unionMemberAt(index, at);
                if (pool.keyOf(member) == .type_unit) continue;
                try backend.writeTypeName(w, member, depth + 1);
                try w.print(" m{d}; ", .{at});
            }
            try w.writeAll("}; uint8_t tag; ");
        },
        .type_struct => |instance| {
            // on demand, because naming a type is not yet needing its fields
            try comp.ensureRows(instance);
            if (comp.instanceAt(instance).rows_state != .done) {
                return error.Refused;
            }
            const rows = comp.instanceAt(instance).rows;
            var position: u32 = 0;
            while (position < rows.len) : (position += 1) {
                // by index, because a field's own struct can grow the rows table
                const row = comp.rowAt(.from(rows.at(position)));
                try backend.writeTypeName(w, row.type, depth + 1);
                try w.print(" f{d} /* {s} */; ", .{ position, pool.stringText(row.name) });
            }
        },
        else => unreachable,
    }
    try w.writeAll("}; // ");
    try spell.writeType(comp, w, index);
    try w.writeByte('\n');

    try backend.types.writer.writeAll(body.written());
}

// constants

const ConstantContext = enum { expression, initializer };

fn writeConstant(
    backend: *C,
    writer: *Writer,
    index: Pool.Index,
    context: ConstantContext,
    depth: u32,
) Fail!void {
    assert(depth < type_depth_max);
    const pool = &backend.comp.pool;

    switch (pool.keyOf(index)) {
        .value_int => |it| try writeIntValue(writer, it),
        .value_float => |it| try writeFloatValue(writer, it),
        .value_unit => try writer.writeAll("0"),
        .value_union => |it| try backend.writeUnionConstant(writer, it, context, depth),
        .value_slice => |it| {
            try backend.ensureStored(it.data, depth);
            const view = pool.keyOf(it.type).type_slice;
            try backend.writeCast(writer, it.type, context, depth);
            try writer.writeAll("{ (");
            try backend.writeTypeName(writer, view.child, depth);
            try writer.print("*)pd{d}.elems, {d} }}", .{
                it.data.int(),
                pool.aggregateLen(it.data),
            });
            try writeCastClose(writer, context);
        },
        .value_aggregate, .value_splat => {
            const type_index = pool.typeOfValue(index);
            // the checker lands every committed constant on a real type
            const of_struct = pool.keyOf(type_index) == .type_struct;
            if (of_struct == false) assert(pool.keyOf(type_index) == .type_array);
            try backend.writeCast(writer, type_index, context, depth);
            if (of_struct) {
                try backend.writeFields(writer, index, depth);
            } else {
                try backend.writeElements(writer, index, depth);
            }
            try writeCastClose(writer, context);
        },
        .type_simple, .type_pointer, .type_array, .type_slice => unreachable,
        .type_struct, .type_unit, .type_union => unreachable,
    }
}

/// A compound in expression position spells its type, `((T){ ... })`, and
/// inside braces it stands bare.
fn writeCast(
    backend: *C,
    writer: *Writer,
    type_index: Pool.Index,
    context: ConstantContext,
    depth: u32,
) Fail!void {
    if (context != .expression) return;
    try writer.writeAll("((");
    try backend.writeTypeName(writer, type_index, depth);
    try writer.writeByte(')');
}

fn writeCastClose(writer: *Writer, context: ConstantContext) Fail!void {
    if (context == .expression) try writer.writeByte(')');
}

/// `{ .f0 = ..., .f1 = ... }`, fields in declaration order.
fn writeFields(backend: *C, writer: *Writer, index: Pool.Index, depth: u32) Fail!void {
    const pool = &backend.comp.pool;
    assert(pool.keyOf(index) == .value_aggregate);
    const count = pool.aggregateLen(index);

    try writer.writeByte('{');
    var at: u64 = 0;
    while (at < count) : (at += 1) {
        if (at > 0) try writer.writeByte(',');
        try writer.print(" .f{d} = ", .{at});
        try backend.writeConstant(writer, pool.aggregateAt(index, at), .initializer, depth + 1);
    }
    try writer.writeAll(" }");
}

/// `{ .elems = { ... } }`, a splat spelled once with a GNU range.
fn writeElements(backend: *C, writer: *Writer, index: Pool.Index, depth: u32) Fail!void {
    const pool = &backend.comp.pool;
    const count = pool.aggregateLen(index);

    try writer.writeAll("{ .elems = {");
    if (pool.keyOf(index) == .value_splat) {
        if (count > 0) {
            try writer.print(" [0 ... {d}] = ", .{count - 1});
            try backend.writeConstant(writer, pool.aggregateAt(index, 0), .initializer, depth + 1);
        }
    } else {
        var at: u64 = 0;
        while (at < count) : (at += 1) {
            if (at > 0) try writer.writeByte(',');
            try writer.writeByte(' ');
            try backend.writeConstant(writer, pool.aggregateAt(index, at), .initializer, depth + 1);
        }
    }
    try writer.writeAll(" } }");
}

fn writeUnionConstant(
    backend: *C,
    writer: *Writer,
    it: Pool.Key.Wrapped,
    context: ConstantContext,
    depth: u32,
) Fail!void {
    const pool = &backend.comp.pool;
    const member = pool.typeOfValue(it.value);
    const position = pool.unionMemberPosition(it.type, member).?;

    switch (unionFormOf(pool, it.type)) {
        .tag_only => try writer.print("{d}", .{position}),
        .niche => |carrier| {
            if (member == carrier) {
                return backend.writeConstant(writer, it.value, context, depth + 1);
            }
            // the null address stands for the unit member
            switch (pool.keyOf(carrier)) {
                .type_pointer => try writer.writeAll("0"),
                .type_slice => {
                    try backend.writeCast(writer, carrier, context, depth);
                    try writer.writeAll("{ 0, 0 }");
                    try writeCastClose(writer, context);
                },
                else => unreachable,
            }
        },
        .tagged => {
            try backend.writeCast(writer, it.type, context, depth);
            if (pool.keyOf(member) == .type_unit) {
                try writer.print("{{ .tag = {d} }}", .{position});
            } else {
                try writer.print("{{ .m{d} = ", .{position});
                try backend.writeConstant(writer, it.value, .initializer, depth + 1);
                try writer.print(", .tag = {d} }}", .{position});
            }
            try writeCastClose(writer, context);
        },
    }
}

fn writeIntValue(writer: *Writer, it: Pool.Key.Int) Fail!void {
    // committed refs always landed on a type, so the width is known
    assert(Pool.isSizedInt(it.type));
    assert(Pool.fitsInt(it.value, it.type));

    // a static simple type shares its value with `SimpleType`, by construction
    const cast = simpleName(@enumFromInt(it.type.int()));

    if (signedIntType(it.type)) {
        if (it.value == Pool.minInt(it.type)) {
            // the lowest value has no literal of its own in C
            try writer.print("(({s})(-{d}LL - 1))", .{ cast, -(it.value + 1) });
        } else {
            try writer.print("(({s}){d}LL)", .{ cast, it.value });
        }
    } else {
        try writer.print("(({s}){d}ULL)", .{ cast, it.value });
    }
}

fn signedIntType(index: Pool.Index) bool {
    return switch (index) {
        .i8_type, .i16_type, .i32_type, .i64_type => true,
        .u8_type, .u16_type, .u32_type, .u64_type => false,
        else => unreachable,
    };
}

fn writeFloatValue(writer: *Writer, it: Pool.Key.Float) Fail!void {
    assert(Pool.isFloat(it.type));
    assert(it.type != .untyped_float_type);

    const cast: []const u8 = if (it.type == .f32_type) "float" else "double";
    if (std.math.isNan(it.value)) {
        return writer.print("(({s})__builtin_nan(\"\"))", .{cast});
    }
    if (std.math.isInf(it.value)) {
        const sign: []const u8 = if (it.value < 0) "-" else "";
        return writer.print("(({s}){s}__builtin_inf())", .{ cast, sign });
    }
    try writer.print("(({s}){x})", .{ cast, it.value });
}

/// The bytes a view points at in static storage.
fn ensureStored(backend: *C, index: Pool.Index, depth: u32) Fail!void {
    assert(depth < type_depth_max);
    const pool = &backend.comp.pool;
    const type_index = pool.typeOfValue(index);
    assert(pool.keyOf(type_index) == .type_array);

    const gop = try backend.stored.getOrPut(backend.gpa, index);
    if (gop.found_existing) return;

    try backend.ensureStoredDeps(index, depth);

    const w = &backend.data.writer;
    try w.writeAll("static const ");
    try backend.writeTypeName(w, type_index, depth);
    try w.print(" pd{d} = ", .{index.int()});
    try backend.writeElements(w, index, depth);
    try w.writeAll(";\n");
}

/// Every storage line a constant will mention, written before its own.
fn ensureStoredDeps(backend: *C, index: Pool.Index, depth: u32) Fail!void {
    assert(depth < type_depth_max);
    const pool = &backend.comp.pool;

    switch (pool.keyOf(index)) {
        .value_slice => |it| try backend.ensureStored(it.data, depth + 1),
        .value_union => |it| try backend.ensureStoredDeps(it.value, depth + 1),
        .value_aggregate, .value_splat => {
            // one element stands for a whole splat
            const count = if (pool.keyOf(index) == .value_splat)
                @min(pool.aggregateLen(index), 1)
            else
                pool.aggregateLen(index);
            var at: u64 = 0;
            while (at < count) : (at += 1) {
                try backend.ensureStoredDeps(pool.aggregateAt(index, at), depth + 1);
            }
        },
        .value_int, .value_float, .value_unit => {},
        .type_simple, .type_pointer, .type_array, .type_slice => unreachable,
        .type_struct, .type_unit, .type_union => unreachable,
    }
}

// functions

/// `    v{n} = `, opening the statement that fills a declared value.
const Assign = struct { local: u32 };
/// `v{n}`, a declared value standing inside an expression.
const Value = struct { local: u32 };
/// What a pointer ref points at, a local slot read as itself.
const Deref = struct { ref: Ref };
/// The ref as an unsigned 64-bit count, sign-widened the way `bounds_check` states.
const Widened = struct { ref: Ref };
/// The address of the first element, behind a slice or an array pointer.
const Base = struct { ref: Ref };

fn assign(local: u32) Assign {
    return .{ .local = local };
}
fn value(local: u32) Value {
    return .{ .local = local };
}
fn deref(ref: Ref) Deref {
    return .{ .ref = ref };
}
fn widened(ref: Ref) Widened {
    return .{ .ref = ref };
}
fn base(ref: Ref) Base {
    return .{ .ref = ref };
}
fn int(type_index: Pool.Index, raw: i128) Pool.Key.Int {
    return .{ .type = type_index, .value = raw };
}

/// One run of C into the code
fn put(backend: *C, parts: anytype) Fail!void {
    const w = &backend.code.writer;
    inline for (parts) |part| {
        switch (@TypeOf(part)) {
            Assign => try w.print("    v{d} = ", .{part.local}),
            Value => try w.print("v{d}", .{part.local}),
            Deref => try backend.writeDeref(part.ref),
            Widened => try backend.writeWidened(part.ref),
            Base => try backend.writeBase(part.ref),
            Ref => try backend.writeRef(part),
            Pool.Index => try backend.writeTypeName(w, part, 0),
            Pool.Key.Int => try writeIntValue(w, part),
            else => switch (@typeInfo(@TypeOf(part))) {
                .int, .comptime_int => try w.print("{d}", .{part}),
                else => try w.writeAll(part),
            },
        }
    }
}

/// An instruction result, or a constant spelled in expression position.
fn writeRef(backend: *C, ref: Ref) Fail!void {
    const w = &backend.code.writer;
    switch (ref.unwrap()) {
        .constant => |constant| try backend.writeConstant(w, constant, .expression, 0),
        .inst => |inst| if (backend.instOf(inst.int()).tag == .local) {
            try w.print("(&s{d})", .{inst.int()});
        } else {
            try w.print("v{d}", .{inst.int()});
        },
    }
}

fn writeDeref(backend: *C, ref: Ref) Fail!void {
    assert(backend.comp.pool.keyOf(backend.typeOfRef(ref)) == .type_pointer);
    switch (ref.unwrap()) {
        .inst => |inst| if (backend.instOf(inst.int()).tag == .local) {
            return backend.code.writer.print("s{d}", .{inst.int()});
        },
        .constant => {},
    }
    try backend.put(.{ "(*", ref, ")" });
}

fn writeWidened(backend: *C, ref: Ref) Fail!void {
    const found = backend.typeOfRef(ref);
    assert(Pool.isSizedInt(found));

    try backend.code.writer.writeAll("(uint64_t)");
    if (signedIntType(found)) try backend.code.writer.writeAll("(int64_t)");
    try backend.writeRef(ref);
}

fn writeBase(backend: *C, ref: Ref) Fail!void {
    const pool = &backend.comp.pool;
    switch (pool.keyOf(backend.typeOfRef(ref))) {
        .type_slice => try backend.put(.{ ref, ".ptr" }),
        .type_pointer => |pointer| {
            assert(pool.keyOf(pointer.child) == .type_array);
            try backend.put(.{ ref, "->elems" });
        },
        else => unreachable,
    }
}

fn instOf(backend: *const C, local: u32) IR.Inst {
    return backend.comp.instAt(backend.func.insts.at(local));
}

fn typeOfRef(backend: *const C, ref: Ref) Pool.Index {
    return switch (ref.unwrap()) {
        .constant => |constant| backend.comp.pool.typeOfValue(constant),
        .inst => |inst| backend.instOf(inst.int()).type,
    };
}

/// The field's position inside its struct, which names the C member.
fn fieldPosition(backend: *const C, ref: Ref, row: Compilation.Row.Index) u32 {
    const pool = &backend.comp.pool;

    const found = backend.typeOfRef(ref);
    const owner = switch (pool.keyOf(found)) {
        .type_pointer => |pointer| pointer.child,
        else => found,
    };
    const rows = backend.comp.instanceAt(pool.keyOf(owner).type_struct).rows;
    assert(row.int() >= rows.start);
    assert(row.int() < rows.end());
    return row.int() - rows.start;
}

fn writeFunc(backend: *C, instance: Pool.Instance, func: IR.Func) Fail!void {
    const comp = backend.comp;
    const w = &backend.code.writer;
    backend.func = func;

    try w.writeAll("// fn ");
    try spell.writeInstance(comp, w, instance);
    try w.writeByte('\n');
    try backend.writeSignature(w, instance, .local);
    try w.writeAll(" {\n");

    // the body opens with one param instruction per row, which the signature bound
    for (comp.instanceRows(instance), 0..) |row, position| {
        const inst = comp.instAt(func.insts.at(@intCast(position)));
        assert(inst.tag == .param);
        assert(inst.type == row.type);
    }

    // every value up front
    var local: u32 = 0;
    while (local < func.insts.len) : (local += 1) try backend.writeDeclaration(local);
    try w.writeByte('\n');

    const blocks = comp.funcBlocks(func);
    assert(blocks.len > 0);
    for (blocks, 0..) |block, raw| {
        try w.print("b{d}:;\n", .{raw});
        var at = block.first;
        while (at < block.end()) : (at += 1) try backend.writeInst(at);
        try backend.writeTerminator(block.terminator);
    }
    try w.writeAll("}\n\n");
}

/// The declaration an instruction's value needs, if it produces one.
fn writeDeclaration(backend: *C, local: u32) Fail!void {
    const pool = &backend.comp.pool;
    const w = &backend.code.writer;
    const inst = backend.instOf(local);

    switch (inst.tag) {
        // bound by the signature already
        .param => assert(local < backend.comp.instanceRows(backend.func.instance).len),
        .local => {
            try backend.put(.{ "    ", pool.keyOf(inst.type).type_pointer.child });
            try w.print(" s{d};", .{local});
            if (inst.data.name != .empty) {
                try w.print(" // {s}", .{pool.stringText(inst.data.name)});
            }
            try w.writeByte('\n');
        },
        else => if (inst.type != .void_type) {
            try backend.put(.{ "    ", inst.type });
            try w.print(" v{d};\n", .{local});
        } else switch (inst.tag) {
            // of the effects, only the compiler's own tests carry a value
            .cmp_eq, .cmp_ne, .cmp_lt, .cmp_le, .cmp_gt, .cmp_ge, .union_is => {
                try w.print("    int v{d};\n", .{local});
            },
            else => {},
        },
    }
}

fn writeInst(backend: *C, local: u32) Fail!void {
    const comp = backend.comp;
    const pool = &comp.pool;
    const inst = backend.instOf(local);

    switch (inst.tag) {
        // both stand declared at the top of the function
        .param => assert(local < comp.instanceRows(backend.func.instance).len),
        .local => assert(pool.keyOf(inst.type).type_pointer.mutable),

        .load => try backend.put(.{ assign(local), deref(inst.data.un), ";\n" }),
        .store => try backend.put(.{
            "    ", deref(inst.data.bin.lhs), " = ", inst.data.bin.rhs, ";\n",
        }),

        .add, .sub, .mul => try backend.writeArith(local, inst),
        .div => try backend.writeDiv(local, inst),
        .mod => try backend.writeMod(local, inst),
        .bit_and, .bit_or, .bit_xor => {
            assert(Pool.isSizedInt(inst.type));
            try backend.writeBinary(local, inst, switch (inst.tag) {
                .bit_and => " & ",
                .bit_or => " | ",
                .bit_xor => " ^ ",
                else => unreachable,
            });
        },
        .shift_left, .shift_right => try backend.writeShift(local, inst),
        .cmp_eq => try backend.writeCompare(local, inst, " == "),
        .cmp_ne => try backend.writeCompare(local, inst, " != "),
        .cmp_lt => try backend.writeCompare(local, inst, " < "),
        .cmp_le => try backend.writeCompare(local, inst, " <= "),
        .cmp_gt => try backend.writeCompare(local, inst, " > "),
        .cmp_ge => try backend.writeCompare(local, inst, " >= "),

        .negate => try backend.writeNegate(local, inst),
        .not => {
            // `not` runs on a bool, two units around one tag byte
            assert(unionFormOf(pool, inst.type) == .tag_only);
            assert(pool.unionMemberCount(inst.type) == 2);
            try backend.put(.{ assign(local), inst.data.un, " ^ 1;\n" });
        },
        .bit_not => try backend.put(.{ assign(local), "(", inst.type, ")~", inst.data.un, ";\n" }),

        .ptr_cast, .int_widen, .float_widen => try backend.put(.{
            assign(local), "(", inst.type, ")", inst.data.un, ";\n",
        }),
        .int_cast => try backend.writeIntCast(local, inst),

        .union_init => try backend.writeUnionInit(local, inst),
        .union_is => try backend.writeUnionIs(local, inst),
        .union_narrow => try backend.writeUnionNarrow(local, inst),

        .bounds_check, .order_check => {
            const operator: []const u8 = if (inst.tag == .bounds_check) " >= " else " > ";
            try backend.put(.{ "    if (", widened(inst.data.bin.lhs), operator });
            try backend.put(.{ widened(inst.data.bin.rhs), ") __builtin_trap();\n" });
        },

        .slice_len => {
            assert(inst.type == .u64_type);
            try backend.put(.{ assign(local), inst.data.un, ".len;\n" });
        },
        .slice_ptr => try backend.put(.{ assign(local), inst.data.un, ".ptr;\n" }),
        .slice_make => {
            const made = IR.sliceMakeAt(comp.funcExtra(backend.func), inst.data.payload);
            try backend.put(.{ assign(local), "(", inst.type, "){ ", base(made.base) });
            // the order check proved start at most end, so the count cannot wrap
            try backend.put(.{ " + ", made.start, ", (uint64_t)(", made.end, " - ", made.start });
            try backend.put(.{") };\n"});
        },
        .elem_ptr => try backend.put(.{
            assign(local), base(inst.data.bin.lhs), " + ", inst.data.bin.rhs, ";\n",
        }),

        .call => try backend.writeCall(local, inst),
        .aggregate_init => try backend.writeAggregateInit(local, inst),

        .field_ptr, .field_val => {
            const field = inst.data.field;
            const position = backend.fieldPosition(field.base, field.row);
            if (inst.tag == .field_ptr) {
                try backend.put(.{ assign(local), "&", field.base, "->f", position, ";\n" });
            } else {
                try backend.put(.{ assign(local), field.base, ".f", position, ";\n" });
            }
        },
    }
}

/// `v = lhs op rhs`, the shape every plain binary lands on.
fn writeBinary(backend: *C, local: u32, inst: IR.Inst, operator: []const u8) Fail!void {
    const bin = inst.data.bin;
    try backend.put(.{ assign(local), bin.lhs, operator, bin.rhs, ";\n" });
}

/// Checked by the builtin, so the sum that does not fit stops the program.
fn writeArith(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const operator, const builtin = switch (inst.tag) {
        .add => .{ " + ", "__builtin_add_overflow" },
        .sub => .{ " - ", "__builtin_sub_overflow" },
        .mul => .{ " * ", "__builtin_mul_overflow" },
        else => unreachable,
    };
    if (Pool.isFloat(inst.type)) return backend.writeBinary(local, inst, operator);

    assert(Pool.isSizedInt(inst.type));
    const bin = inst.data.bin;
    try backend.put(.{ "    if (", builtin, "(", bin.lhs, ", ", bin.rhs, ", &", value(local) });
    try backend.put(.{")) __builtin_trap();\n"});
}

fn writeDiv(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const bin = inst.data.bin;
    try backend.put(.{ "    if (", bin.rhs, " == 0) __builtin_trap();\n" });

    if (Pool.isSizedInt(inst.type) and signedIntType(inst.type)) {
        // the one quotient that does not fit is the lowest value over minus one
        try backend.put(.{ "    if (", bin.lhs, " == ", int(inst.type, Pool.minInt(inst.type)) });
        try backend.put(.{ " && ", bin.rhs, " == -1) __builtin_trap();\n" });
    }
    try backend.writeBinary(local, inst, " / ");
}

fn writeMod(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    assert(Pool.isSizedInt(inst.type));
    const bin = inst.data.bin;
    try backend.put(.{ "    if (", bin.rhs, " == 0) __builtin_trap();\n" });

    try backend.put(.{assign(local)});
    if (signedIntType(inst.type)) {
        // the C remainder of the lowest value over minus one is undefined, ours is zero
        try backend.put(.{ "(", bin.rhs, " == -1) ? 0 : " });
    }
    try backend.put(.{ bin.lhs, " % ", bin.rhs, ";\n" });
}

/// Left shifts run unsigned so the bits shifted out are lost rather than undefined.
fn writeShift(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    assert(Pool.isSizedInt(inst.type));
    const bin = inst.data.bin;
    const width = Pool.widthOf(inst.type);

    try backend.put(.{ "    if (", widened(bin.rhs), " >= ", width, ") __builtin_trap();\n" });
    try backend.put(.{ assign(local), "(", inst.type, ")" });
    if (inst.tag == .shift_left) {
        try backend.put(.{ "((uint", width, "_t)", bin.lhs, " << ", bin.rhs, ")" });
    } else {
        // arithmetic on the signed types, which every supported compiler keeps
        try backend.put(.{ "(", bin.lhs, " >> ", bin.rhs, ")" });
    }
    try backend.put(.{";\n"});
}

/// The compiler's own test answers C truth, the file's answers a bool, tag zero true.
fn writeCompare(backend: *C, local: u32, inst: IR.Inst, operator: []const u8) Fail!void {
    if (inst.type == .void_type) return backend.writeBinary(local, inst, operator);

    assert(unionFormOf(&backend.comp.pool, inst.type) == .tag_only);
    const bin = inst.data.bin;
    try backend.put(.{ assign(local), "!(", bin.lhs, operator, bin.rhs, ");\n" });
}

fn writeNegate(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    if (Pool.isFloat(inst.type)) {
        return backend.put(.{ assign(local), "-", inst.data.un, ";\n" });
    }

    // subtraction from zero, so the lowest value traps instead of overflowing
    assert(Pool.isSizedInt(inst.type));
    assert(signedIntType(inst.type));
    try backend.put(.{ "    if (__builtin_sub_overflow((", inst.type, ")0, ", inst.data.un });
    try backend.put(.{ ", &", value(local), ")) __builtin_trap();\n" });
}

/// The number where the destination holds it, the union's other member where not.
fn writeIntCast(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const pool = &backend.comp.pool;
    const operand = inst.data.un;

    assert(unionFormOf(pool, inst.type) == .tagged);
    assert(pool.unionMemberCount(inst.type) == 2);
    const wanted = pool.unionMemberAt(inst.type, 0);
    assert(Pool.isSizedInt(wanted));
    assert(pool.keyOf(pool.unionMemberAt(inst.type, 1)) == .type_unit);

    const source = backend.typeOfRef(operand);
    assert(Pool.isSizedInt(source));

    // the fit test, in 64 bits, with the signs the two types actually have
    try backend.put(.{"    if ("});
    if (signedIntType(source)) {
        if (signedIntType(wanted)) {
            try backend.put(.{ "(int64_t)", operand, " >= ", int(.i64_type, Pool.minInt(wanted)) });
            try backend.put(.{ " && (int64_t)", operand, " <= " });
            try backend.put(.{int(.i64_type, Pool.maxInt(wanted))});
        } else {
            try backend.put(.{ operand, " >= 0 && (uint64_t)", operand, " <= " });
            try backend.put(.{int(.u64_type, Pool.maxInt(wanted))});
        }
    } else {
        try backend.put(.{ "(uint64_t)", operand, " <= ", int(.u64_type, Pool.maxInt(wanted)) });
    }

    try backend.put(.{ ") ", value(local), " = (", inst.type, "){ .m0 = (", wanted, ")", operand });
    try backend.put(.{ ", .tag = 0 }; else ", value(local), " = (", inst.type });
    try backend.put(.{"){ .tag = 1 };\n"});
}

fn writeUnionInit(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const pool = &backend.comp.pool;
    const member = inst.data.probe.member;
    const operand = inst.data.probe.operand;

    if (pool.isUnion(member)) return backend.refuse(inst.node, "a union widening");
    // the member the checker admitted, so membership is its promise
    const position = pool.unionMemberPosition(inst.type, member).?;

    try backend.put(.{assign(local)});
    switch (unionFormOf(pool, inst.type)) {
        .tag_only => {
            assert(pool.keyOf(member) == .type_unit);
            try backend.put(.{position});
        },
        .niche => |carrier| if (member == carrier) {
            try backend.put(.{operand});
        } else {
            // the null address stands for the unit member
            assert(pool.keyOf(member) == .type_unit);
            switch (pool.keyOf(carrier)) {
                .type_pointer => try backend.put(.{"0"}),
                .type_slice => try backend.put(.{ "(", carrier, "){ 0, 0 }" }),
                else => unreachable,
            }
        },
        .tagged => if (pool.keyOf(member) == .type_unit) {
            try backend.put(.{ "(", inst.type, "){ .tag = ", position, " }" });
        } else {
            try backend.put(.{ "(", inst.type, "){ .m", position, " = ", operand });
            try backend.put(.{ ", .tag = ", position, " }" });
        },
    }
    try backend.put(.{";\n"});
}

fn writeUnionIs(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const probe = inst.data.probe;

    try backend.put(.{assign(local)});
    if (inst.type == .void_type) {
        try backend.writeMemberTest(probe.operand, probe.member);
    } else {
        assert(unionFormOf(&backend.comp.pool, inst.type) == .tag_only);
        try backend.put(.{"!("});
        try backend.writeMemberTest(probe.operand, probe.member);
        try backend.put(.{")"});
    }
    try backend.put(.{";\n"});
}

fn writeUnionNarrow(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const pool = &backend.comp.pool;
    const source = backend.typeOfRef(inst.data.un);
    assert(pool.isUnion(source));

    if (pool.isUnion(inst.type)) {
        return backend.refuse(inst.node, "a union narrowing to a union");
    }
    const position = pool.unionMemberPosition(source, inst.type).?;

    try backend.put(.{assign(local)});
    switch (unionFormOf(pool, source)) {
        .tag_only => try backend.put(.{"0"}),
        .niche => |carrier| if (inst.type == carrier) {
            try backend.put(.{inst.data.un});
        } else {
            assert(pool.keyOf(inst.type) == .type_unit);
            try backend.put(.{"0"});
        },
        .tagged => if (pool.keyOf(inst.type) == .type_unit) {
            try backend.put(.{"0"});
        } else {
            try backend.put(.{ inst.data.un, ".m", position });
        },
    }
    try backend.put(.{";\n"});
}

/// C truth for whether the union ref holds the member.
fn writeMemberTest(backend: *C, ref: Ref, member: Pool.Index) Fail!void {
    const pool = &backend.comp.pool;
    const source = backend.typeOfRef(ref);
    assert(pool.isUnion(source));
    const position = pool.unionMemberPosition(source, member).?;

    switch (unionFormOf(pool, source)) {
        .tag_only => try backend.put(.{ ref, " == ", position }),
        .niche => |carrier| {
            try backend.put(.{ref});
            if (pool.keyOf(carrier) == .type_slice) try backend.put(.{".ptr"});
            try backend.put(.{if (member == carrier) " != 0" else " == 0"});
        },
        .tagged => try backend.put(.{ ref, ".tag == ", position }),
    }
}

fn writeCall(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const comp = backend.comp;
    const w = &backend.code.writer;
    const call = IR.callAt(comp.funcExtra(backend.func), inst.data.payload);
    const callee = comp.declAt(comp.instanceDecl(call.callee));

    if (inst.type == .void_type) {
        try w.writeAll("    ");
    } else {
        try backend.put(.{assign(local)});
    }
    switch (callee.kind) {
        .extern_fn => {
            try backend.ensureExtern(call.callee);
            try w.writeAll(comp.pool.stringText(callee.name));
        },
        .fn_decl => {
            // whole-program lowering, so the body of every callee committed
            assert(comp.instanceAt(call.callee).func != .none);
            try writeFuncName(comp, w, call.callee);
        },
        else => unreachable,
    }
    try w.writeByte('(');
    for (call.args, 0..) |argument, position| {
        if (position > 0) try w.writeAll(", ");
        try backend.writeRef(argument);
    }
    try w.writeAll(");\n");
}

fn writeAggregateInit(backend: *C, local: u32, inst: IR.Inst) Fail!void {
    const pool = &backend.comp.pool;
    const w = &backend.code.writer;
    const elements = IR.aggregateInitAt(backend.comp.funcExtra(backend.func), inst.data.payload);
    const of_struct = pool.keyOf(inst.type) == .type_struct;

    if (of_struct) {
        const instance = pool.keyOf(inst.type).type_struct;
        assert(elements.len == backend.comp.instanceAt(instance).rows.len);
    } else {
        assert(elements.len == pool.keyOf(inst.type).type_array.len);
    }

    try backend.put(.{ assign(local), "(", inst.type, ")" });
    try w.writeAll(if (of_struct) "{" else "{ .elems = {");
    for (elements, 0..) |element, position| {
        if (position > 0) try w.writeByte(',');
        if (of_struct) try w.print(" .f{d} = ", .{position}) else try w.writeByte(' ');
        try backend.writeRef(element);
    }
    try w.writeAll(if (of_struct) " };\n" else " } };\n");
}

fn writeTerminator(backend: *C, terminator: IR.Terminator) Fail!void {
    switch (terminator) {
        // `finishFunc` left every surviving block a terminator
        .none => unreachable,
        .jump => |target| try backend.put(.{ "    goto b", target.int(), ";\n" }),
        .branch => |branch| {
            try backend.put(.{"    if ("});
            try backend.writeCondition(branch.cond);
            try backend.put(.{ ") goto b", branch.then_block.int() });
            try backend.put(.{ "; else goto b", branch.else_block.int(), ";\n" });
        },
        .ret => |returned| if (returned == .none) {
            try backend.put(.{"    return;\n"});
        } else {
            try backend.put(.{ "    return ", returned, ";\n" });
        },
        .trap => try backend.put(.{"    __builtin_trap();\n"}),
    }
}

fn writeCondition(backend: *C, cond: Ref) Fail!void {
    const pool = &backend.comp.pool;
    const found = backend.typeOfRef(cond);

    if (found == .void_type) return backend.writeRef(cond);

    assert(pool.isUnion(found));
    try backend.writeMemberTest(cond, pool.firstMember(found));
}

fn refuse(backend: *C, node: AST.Node.Index, what: []const u8) Fail {
    @branchHint(.cold);
    const comp = backend.comp;
    const decl = comp.declAt(comp.instanceDecl(backend.func.instance));
    comp.reportNode(decl.module, node, .{
        .code = .backend_unsupported,
        .message = comp.fmt("the C backend does not compile {s} yet", .{what}) catch
            return error.OutOfMemory,
        .label = "cannot build this yet",
        .help = "'phi check' accepts it, and the backend refuses it rather than " ++
            "compiling it wrong",
    }) catch return error.OutOfMemory;
    return error.Refused;
}

const testing = std.testing;

fn testCompile(comp: *Compilation, text: []const u8) !void {
    const gpa = testing.allocator;
    try comp.init(gpa, testing.io, .{ .root_path = "test.phi", .std_dir = null });
    errdefer comp.deinit();

    const buffer = try gpa.alloc(u8, text.len + Source.padding);
    @memcpy(buffer[0..text.len], text);
    buffer[text.len] = 0;
    try comp.compile(.{ .path = "test.phi", .bytes = buffer[0..text.len :0] });
}

test "the entry is found, missed, or refused" {
    var comp: Compilation = undefined;
    try testCompile(&comp,
        \\fn main() {
        \\}
        \\
    );
    defer comp.deinit();
    try testing.expectEqual(0, comp.diagnostics.items.len);
    try testing.expect(try entryOf(&comp) == .instance);

    var absent: Compilation = undefined;
    try testCompile(&absent,
        \\fn helper() {
        \\}
        \\
    );
    defer absent.deinit();
    try testing.expect(try entryOf(&absent) == .missing);
    try testing.expectEqual(0, absent.diagnostics.items.len);

    var shaped: Compilation = undefined;
    try testCompile(&shaped,
        \\fn main(a: i64) i64 {
        \\    return a
        \\}
        \\
    );
    defer shaped.deinit();
    try testing.expect(try entryOf(&shaped) == .refused);
    try testing.expectEqual(2, shaped.diagnostics.items.len);
}
