// Generated by the Phi compiler. Do not edit.
#include <stdint.h>

typedef struct pt15 pt15;
struct pt15 { int64_t f0 /* x */; int64_t f1 /* y */; }; // Point

static pt15 p1_make(int64_t v0 /* x */);
static int64_t p2_slide(pt15 v0 /* p */);
static void p3_main(void);

// fn make
static pt15 p1_make(int64_t v0 /* x */) {
    int64_t v1;
    pt15 v2;

b0:;
    if (__builtin_add_overflow(v0, ((int64_t)1LL), &v1)) __builtin_trap();
    v2 = (pt15){ .f0 = v0, .f1 = v1 };
    return v2;
}

// fn slide
static int64_t p2_slide(pt15 v0 /* p */) {
    int64_t v1;
    int64_t v2;
    int64_t v3;

b0:;
    v1 = v0.f0;
    v2 = v0.f1;
    if (__builtin_add_overflow(v1, v2, &v3)) __builtin_trap();
    return v3;
}

// fn main
static void p3_main(void) {
    pt15 v0;
    pt15 s1; // p
    int64_t* v3;
    pt15 v4;
    int64_t v5;
    int64_t v6;
    pt15 v8;
    int64_t v9;

b0:;
    v0 = p1_make(((int64_t)20LL));
    s1 = v0;
    v3 = &(&s1)->f1;
    v4 = s1;
    v5 = v4.f0;
    if (__builtin_add_overflow(v5, ((int64_t)22LL), &v6)) __builtin_trap();
    (*v3) = v6;
    v8 = s1;
    v9 = p2_slide(v8);
    return;
}

int main(void) {
    p3_main();
    return 0;
}
